### ISSUE TITLE
Create class QIndex

### ISSUE THREAD

**Issue by AnuarTB** [AnuarTB/immi-cs350#2]
The class QIndex will be responsible for providing information for the quality of life indices for cities/countries.

- [x] Populate database with at least 5 'QIndex' class instances.  
- [x] Implement getFullDescription method for QIndex class.
- [x] Implement getQIndexByName method for ImmIDatabase class.

**Comment by amanzholov8** [comment]
First TODO is done: a494f0da4d2739e997e8ddaaec302b3a8f49fc1b

**Comment by BaurTokenov** [comment]
Second TODO is done: e96af1f7919d8a83c2ab427b65c7ad679eb17a9e
